---
# Corporate Proxy Configuration
proxy_config:
  ug-proxy:
    # Uganda Proxy
    no_proxy: "localhost,127.0.0.1,192.23.12.160,192.25.193.19"
    proxy_host: "192.23.12.211"
    proxy_port: "4145"
    proxy_username: "1234567"
    proxy_password: amu%40lky
    yum_proxy_password: amu@lky
    proxy_user: aessos

corp_http_proxy: 1
corp_https_proxy: 1
corp_yum_http_proxy: 1
corp_yum_https_proxy: 1
corp_no_proxy: 1

# Gradle Configuration
gradle_version: "4.10"
gradle_base_dir: /opt
gradle_link: /usr/local/bin/gradle
