---
- name: "config: create custom log folder for sonar"
  file: 
    path: "{{ sonarqube_loglevel }}"
    owner: sonarqube
    group: sonarqube
    state: directory

- name: adding custom sonar.properties
  template:
    src: sonar.properties.j2
    dest: /usr/local/bin/sonarqube/conf/sonar.properties
    owner: sonarqube
    group: sonarqube
    mode: 0644
  notify: 
    - restarting sonarqube
  tags:
    - test

- name: Adding custom service file
  template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service
    owner: root
    group: root
    mode: 0755
  notify: 
    - restarting sonarqube
    - reload sonarqube

- name: Starting sonarqube
  service:
    name: sonarqube
    state: started
    enabled: yes
...
