---
- name: Install Sonarqube on Debian
  include_tasks: debian.yml
  when:
    ansible_os_family == "Debian"

- name: Install Sonarqube on Redhat
  include_tasks: redhat.yml
  when:
    ansible_os_family == "RedHat"

- name: Include config.yml
  include: config.yml
...
