---
- name: restart td-agent
  systemd:
    name: "td-agent"
    daemon_reload: yes
    enabled: yes
    state: restarted
  run_once: true

- name: reload td-agent
  systemd: name=td-agent state=reloaded
